{% set name = "clonebuildregister" %}

package:
  name: {{ name|lower }}
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git-url: https://github.com/cznethub/clonebuildregister
  path: ../
  

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - python
    - setuptools
  host:
    - python
    - pip
  run:
    - python
    - docker-py
    - gitpython
    - github3.py
    - python-dotenv
    - google-cloud-artifact-registry
    - grpcio-status
  entry_points:
    - clonebuildregister = src.clonebuildregister.__main__:main


about:
  home: https://github.com/cznethub/clonebuildregister
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jnsproul

outputs:
  - name: clonebuildregister
    files:
      exclude:
        - tests/*
