{% set name = "clonebuildregister" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cznethub/clonebuildregister/archive/{{ version }}.tar.gz
  sha256: 5db7b9a2420d00657daed08aaf4cfc27a192b2d68b3b88ff802717561fdc29ba
  path: ../src/
  

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - python
    - setuptools
  host:
    - python
    - pip
  run:
    - python
    - docker-py
    - gitpython
    - github3.py
    - python-dotenv
    - google-cloud-artifact-registry
    - grpcio-status
  entry_points:
    - clonebuildregister = clonebuildregister.__main__:main

test:
  imports:
    - clonebuildregister
  commands:
    - pytest
    - tox -e lint
    - tox -e style
    - tox -e type
  requires:
    - tox
    - pytest

about:
  home: https://github.com/cznethub/clonebuildregister
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jnsproul
