{% set name = "clonebuildregister" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cznethub/clonebuildregister/archive/{{ version }}.tar.gz
  sha256: b963bc5a24a708e3b78a9e4cd871b256086b52e1ae3891782b85c8300f6b3be6
  path: ../src/
  

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - python
    - setuptools
  host:
    - python
    - pip
  run:
    - python
    - docker-py
    - gitpython
    - github3.py
    - python-dotenv
    - google-cloud-artifact-registry
    - grpcio-status
  entry_points:
    - clonebuildregister = clonebuildregister.__main__:main


about:
  home: https://github.com/cznethub/clonebuildregister
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jnsproul
